// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB39A2ACnwu54hlVhepSBmYJk53TGmtURE',
    appId: '1:126453755347:web:771000daca97d6b999d326',
    messagingSenderId: '126453755347',
    projectId: 'long-equinox-419408',
    authDomain: 'long-equinox-419408.firebaseapp.com',
    storageBucket: 'long-equinox-419408.appspot.com',
    measurementId: 'G-0W0WCJS504',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH3x6aZdgco0YQwuCj6iZyjvAiNfP7Yak',
    appId: '1:126453755347:android:72a0e959e3074fb499d326',
    messagingSenderId: '126453755347',
    projectId: 'long-equinox-419408',
    storageBucket: 'long-equinox-419408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOIH44yg2Oiy4eOby57y-zh_PEE8ZqH-M',
    appId: '1:126453755347:ios:16a47ea880b88f0399d326',
    messagingSenderId: '126453755347',
    projectId: 'long-equinox-419408',
    storageBucket: 'long-equinox-419408.appspot.com',
    iosBundleId: 'com.example.migrant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOIH44yg2Oiy4eOby57y-zh_PEE8ZqH-M',
    appId: '1:126453755347:ios:d590a9ac1ecc48ce99d326',
    messagingSenderId: '126453755347',
    projectId: 'long-equinox-419408',
    storageBucket: 'long-equinox-419408.appspot.com',
    iosBundleId: 'com.example.migrant.RunnerTests',
  );
}
